import { cookies } from "next/headers";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import { ToastContainer } from 'react-toastify';
import { AuthProvider } from "./context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // 🍪 sunucu tarafında çerezleri oku
  const cookieStore = cookies();
  const token = cookieStore.get("token")?.value || null;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* token'ı AuthProvider'a gönder */}
        <AuthProvider token={token}>
          <Header />
          {children}
        </AuthProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
